# Generated by Django 5.1.3 on 2026-01-21 07:03

import django_ckeditor_5.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGovernanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='corporate_governance/')),
                ('ar_image', models.ImageField(blank=True, help_text='Arabic version of the image', null=True, upload_to='corporate_governance/ar/')),
                ('order', models.IntegerField(default=0, help_text='Display order on the corporate governance page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate Governance Image',
                'verbose_name_plural': 'Corporate Governance Images',
                'db_table': 'home_corporategovernanceimage',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('photos_videos', 'Photos & Videos Page'), ('about', 'About Us Page'), ('news', 'News Page'), ('careers', 'Careers Page'), ('contact', 'Contact Page'), ('heritage', 'Heritage Page'), ('team', 'Team Page'), ('corporate_governance', 'Corporate Governance Page'), ('vision_mission_values', 'Vision, Mission & Values Page'), ('sustainability', 'Sustainability Page'), ('saudi_vision', 'Saudi Vision Page')], max_length=50, unique=True)),
                ('title', models.CharField(help_text='For admin reference only', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Legacy field - use desktop_image instead', null=True, upload_to='hero/')),
                ('desktop_image', models.ImageField(blank=True, help_text='Desktop version (1920x1080px recommended)', null=True, upload_to='hero/desktop/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile version (768x1024px recommended)', null=True, upload_to='hero/mobile/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'db_table': 'home_heroimage',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'db_table': 'home_newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content')),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'db_table': 'home_privacypolicy',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_pdf', models.FileField(blank=True, help_text='Upload the catalogue PDF shown in product pages', null=True, upload_to='catalogues/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'db_table': 'home_siteconfig',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content')),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'db_table': 'home_termsofservice',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pages.category')),
            ],
            options={
                'db_table': 'home_category',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('link', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.category')),
            ],
            options={
                'db_table': 'home_portfolioitem',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('icon', models.FileField(help_text='Upload SVG icon file', upload_to='category_icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('filter_class', models.CharField(help_text='CSS class used for filtering (e.g., filter-beef)', max_length=50)),
                ('level', models.IntegerField(default=0, help_text='0 for main category, 1 for subcategory, 2 for sub-subcategory')),
                ('order', models.IntegerField(default=0, help_text='Order in which the category appears')),
                ('is_active', models.BooleanField(default=True)),
                ('main_category_type', models.CharField(blank=True, choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('oils', 'Oils'), ('others', 'Others')], help_text='Main category type (only for level 0 categories)', max_length=20, null=True)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='pages.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'home_productcategory',
                'ordering': ['level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('shop_link', models.URLField(max_length=500)),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.IntegerField(default=0, help_text='Order in which the product appears')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='products', to='pages.productcategory')),
            ],
            options={
                'db_table': 'home_product',
                'ordering': ['order', 'name'],
            },
        ),
    ]
