# Generated by Django 5.1.3 on 2026-06-17 07:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Content'),
        ),
    ]
