FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=goldenMeatPortfolio.settings.prod

CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn goldenMeatPortfolio.wsgi:application --bind 0.0.0.0:8000"]
