# Generated by Django 5.1.3 on 2026-01-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500)),
                ('description_en', models.CharField(max_length=500, null=True)),
                ('description_ar', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Main image (800x600px recommended)', upload_to='gallery/')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance in the gallery')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'db_table': 'home_galleryphoto',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Related image (800x600px recommended)', upload_to='gallery/related/')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance in the slider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='gallery.galleryphoto')),
            ],
            options={
                'verbose_name': 'Related Gallery Image',
                'verbose_name_plural': 'Related Gallery Images',
                'db_table': 'home_galleryphotoimage',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
