# Generated by Django 5.1.3 on 2026-07-05 15:14

import design.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_componentcategory_icon_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcategory',
            name='depends_on_category',
            field=models.ForeignKey(blank=True, help_text="If set, this category's layer image is resolved against the selected option of the target category (e.g. Mirror depends on Walls).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_categories', to='design.componentcategory', verbose_name='Depends on category'),
        ),
        migrations.CreateModel(
            name='OptionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_image', models.ImageField(help_text='Transparent PNG for this option-on-option combination.', upload_to=design.models.design_projection_path, verbose_name='Projection image')),
                ('depends_on_option', models.ForeignKey(help_text='The option this variant image is painted on, e.g. a wall finish.', on_delete=django.db.models.deletion.CASCADE, related_name='variant_uses', to='design.componentoption', verbose_name='For option')),
                ('option', models.ForeignKey(help_text='The dependent-category option, e.g. a mirror position.', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='design.componentoption', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Option Variant',
                'verbose_name_plural': 'Option Variants',
                'db_table': 'design_optionvariant',
                'unique_together': {('option', 'depends_on_option')},
            },
        ),
    ]
