# Generated by Django 5.1.3 on 2026-07-08 07:25

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_componentcategory_depends_on_category_optionvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentoption',
            name='projection_image',
            field=models.ImageField(blank=True, help_text='Transparent PNG placed on the 2D canvas. All projection images must share the same canvas dimensions. Leave empty for options in a dependent category (e.g. mirrors) — their images are managed per wall in the Option variants matrix.', upload_to=design.models.design_projection_path, verbose_name='Projection image'),
        ),
        migrations.AlterField(
            model_name='componentoption',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Small preview image shown in the selection grid. Optional for options in a dependent category (e.g. mirrors).', upload_to=design.models.design_thumbnail_path, verbose_name='Thumbnail'),
        ),
    ]
