# Generated by Django 5.1.3 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_componentoption_is_default_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCTASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Show the floating "Design Your Elevator" button on the home page.', verbose_name='Show design CTA button')),
            ],
            options={
                'verbose_name': 'Design CTA Button Setting',
                'verbose_name_plural': 'Design CTA Button Setting',
                'db_table': 'design_ctasettings',
            },
        ),
    ]
