# Generated by Django 5.1.3 on 2026-07-24 17:36

import design.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_designctasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcategory',
            name='kind',
            field=models.CharField(choices=[('visual', 'Visual — paints a layer on the cabin preview'), ('sound', 'Sound — the user auditions and picks an audio file')], default='visual', help_text='Visual categories paint an image layer. Sound categories hold audio files instead and render a player in the studio.', max_length=10, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='componentoption',
            name='sound_file',
            field=models.FileField(blank=True, help_text='Audio clip for options in a Sound category. Leave empty for visual categories.', upload_to=design.models.design_sound_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Sound file'),
        ),
    ]
