# Generated by Django 5.1.3 on 2026-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_sound_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('form_email_download', 'Contact form → email the PDF and download it'), ('form_email_only', 'Contact form → email the PDF only'), ('free_download', 'Free download, no contact form')], default='form_email_download', help_text='Controls whether visitors must submit their contact details to get the PDF.', max_length=32, verbose_name='PDF delivery mode')),
            ],
            options={
                'verbose_name': 'Design Export Setting',
                'verbose_name_plural': 'Design Export Setting',
                'db_table': 'design_exportsettings',
            },
        ),
    ]
