# Generated by Django 5.1.3 on 2026-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_designexportsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignLeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('selections_summary', models.TextField(blank=True, help_text='Snapshot of the cabin the visitor designed, kept as text so it survives later edits to the component catalogue.', verbose_name='Chosen components')),
                ('design_url', models.URLField(blank=True, max_length=500, verbose_name='Design link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
            ],
            options={
                'verbose_name': 'Design Lead',
                'verbose_name_plural': 'Design Leads',
                'db_table': 'design_leadsubmission',
                'ordering': ['-created_at'],
            },
        ),
    ]
