# Generated by Django 5.1.3 on 2026-06-17 07:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_email_jobapplication_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
