# Generated by Django 5.1.3 on 2026-01-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_galleryphoto_history_and_more'),
    ]

    operations = [
    ]
