# Generated by Django 5.1.3 on 2026-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsubmission',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
