# Generated by Django 5.1.3 on 2026-01-21 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For admin reference only', max_length=200)),
                ('desktop_image', models.ImageField(blank=True, help_text='Desktop version of the slide (1920x1080 recommended)', null=True, upload_to='carousel/desktop/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile version of the slide (768x1024 recommended)', null=True, upload_to='carousel/mobile/')),
                ('ar_desktop_image', models.ImageField(blank=True, help_text='Arabic desktop version of the slide (1920x1080 recommended)', null=True, upload_to='carousel/desktop/ar/')),
                ('ar_mobile_image', models.ImageField(blank=True, help_text='Arabic mobile version of the slide (768x1024 recommended)', null=True, upload_to='carousel/mobile/ar/')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance in the carousel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'db_table': 'home_carouselslide',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For admin reference only', max_length=200)),
                ('video_file', models.FileField(help_text='Upload MP4 video file', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Video',
                'verbose_name_plural': 'Home Video',
                'db_table': 'home_homevideo',
            },
        ),
    ]
