# Generated by Django 5.1.3 on 2026-01-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_report_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcategory',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Select an icon from the list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='financial.reporticon'),
        ),
    ]
